---
language: go

go:
  - 1.9.x
  - tip

services:
  - docker

matrix:
  allow_failures:
    - tip
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - curl -sLo temp.zip https://github.com/golang/dep/releases/download/v0.3.0/dep-linux-amd64.zip
  - unzip temp.zip
  - rm temp.zip
  - cp dep $HOME/gopath/bin/

script:
  - make testdeps
  - make build
  - make test
  - make testdocs
  - make integration
