---
language: go

go:
  - 1.8.x
  - tip

services:
  - docker

matrix:
  allow_failures:
    - tip
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

install:
  - go get github.com/kardianos/govendor

script:
  - make testdeps
  - make build
  - make test
  - make testdocs
  - make integration
