---
language: go

go:
  - 1.8.x
  - tip

services:
  - docker

matrix:
  allow_failures:
    - tip
  fast_finish: true

install:
  - go get github.com/kardianos/govendor

script:
  - make testdeps
  - make test
  - make testdocs
  - make integration
