global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

remote_write:
  - url: http://athensdb_1:9080/receive
  - url: http://athensdb_2:9080/receive
  - url: http://athensdb_3:9080/receive
