version: '3.2'
services:
  athensdb:
    build: ../
    ports:
      - 9080:9080
  prometheus:
    build: prometheus/
    links:
      - athensdb
  integration-tests:
    build:
      context: ../
      dockerfile: integration_tests/Dockerfile
    links:
      - athensdb
