version: '3.2'
services:
  athensdb_1:
    build: ../
    ports:
      - 9080:9080
    links:
      - athensdb_2
      - athensdb_3
    environment:
      PEERS: athensdb_2,athensdb_3
  athensdb_2:
    build: ../
    ports:
      - 9081:9080
  athensdb_3:
    build: ../
    ports:
      - 9082:9080
    environment:
      PEERS: athensdb_1,athensdb_3
  prometheus:
    image: prom/prometheus:v1.7.1
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.engine=none'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - athensdb_1
      - athensdb_2
      - athensdb_3
    environment:
      PEERS: athensdb_1,athensdb_2
  integration-tests:
    build:
      context: ../
      dockerfile: integration_tests/Dockerfile
    links:
      - athensdb_1
      - athensdb_2
      - athensdb_3
